### ISSUE TITLE
make error while trying to generate/install opensource COBOL on Linux

### ISSUE THREAD

**Issue by sakura90** [opensourcecobol/opensource-cobol#47]
I installed GNU MP (libgmp) successfully in Ubuntu 18.   To generate/install opensource COBOL on Linux, I then ran ./configure and ran successfully.  Then I ran make.  I got some errors. I wanted to restart make, so I ran make clean and afterwards ran make.

The make command did not run successfully.  I got errors and the first error was the following error.  Attached is the full log of the last time I ran make.

rm -f ja.gmo && : -c --statistics -o ja.gmo ja.po
Makefile:123: recipe for target 'ja.gmo' failed

[make.log](https://github.com/opensourcecobol/opensource-cobol/files/7632618/make.log)

Could anybody help?

**Comment by GitMensch** [comment]
Because of the missing release tarball I'd suggest to:

* get the source snapshot, unpack, cd there
* run `autoreconf --verbose --force --include=m4`
* run `configure` as you did
* run `make`

Note: this _may_ not work, it _should **if**_ the autoconf/automake parts are "clean".

Independent of that: if you could post your personal "that feature is most missing for me" list upstream (so either [discussion boards](https://sourceforge.net/p/gnucobol/discussion/help/) or via [mailing list](https://lists.gnu.org/mailman/listinfo/gnucobol-users)) then there would be a chance to actually add it there, too, allowing more people in Japan to use that version.

**Comment by GitMensch** [comment]
@sakura90 "closed" by "I don't care any more", by "that autoreconf worked", by "I've solved this different"?

**Comment by sakura90** [comment]
Seems that it does not matter a lot.  This repository does not have many activities for a few years.  GnuCOBOL is the more updated compiler for COBOL.  For my case, GnuCOBOL instead of this repository is the repository to be looked at.

**Comment by GitMensch** [comment]
As noted: this repo does have some things GC doesn't - so if you see anything that is missing for you in GnuCOBOL please report this via its mailing list or issue trackers.
